### ISSUE TITLE
streams.update(config: StreamConfig) api changed ... update your code.

### ISSUE THREAD

**Issue by kenguru33** [Redningsselskapet/nestjs-plugins#25]
Changes in the Nats API: 

Trace:  >> streams.update(config: StreamConfig) api changed to streams.update(name: string, config: StreamUpdateConfig) - this shim will be removed - update your code.
    at StreamAPIImpl.<anonymous> (/Users/raarts/work/company/group/product/node_modules/nats/nats-base-client/jsmstream_api.ts:73:15)
    at Generator.next (<anonymous>)
    at /Users/raarts/work/company/group/product/node_modules/nats/lib/nats-base-client/jsmstream_api.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/raarts/work/company/group/product/node_modules/nats/lib/nats-base-client/jsmstream_api.js:18:12)
    at StreamAPIImpl.update (/Users/raarts/work/company/group/product/node_modules/nats/lib/nats-base-client/jsmstream_api.js:54:16)
    at NatsJetStreamServer.setupStream (/Users/raarts/work/company/group/product/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/server.ts:121:49)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NatsJetStreamServer.listen (/Users/raarts/work/company/group/product/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/server.ts:36:7)

https://github.com/nats-io/nats.js/issues/488

**Comment by kenguru33** [comment]
fixed

**Comment by amir2227** [comment]
how to fix this
