### ISSUE TITLE
Connects fails with Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kenguru33** [Redningsselskapet/nestjs-plugins#27]
Calling connect from NatsJetStreamClient couses error Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)
    at NatsJetStreamClient.connect (/Users/bernt/Coding/rs-dev/mylab/aistracker/packages/kystverket-aisdata-import/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/nats-jetstream-client.ts:16:10)

**Comment by kenguru33** [comment]
fixed
